// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(RelationalDbContext))]
    [Migration("20251117132621_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Relational.Lekarz", b =>
                {
                    b.Property<int>("IdLekarza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_lekarza");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLekarza"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nazwisko");

                    b.Property<string>("Specjalizacja")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("specjalizacja");

                    b.HasKey("IdLekarza");

                    b.ToTable("lekarz");
                });

            modelBuilder.Entity("Backend.Models.Relational.Pacjent", b =>
                {
                    b.Property<int>("IdPacjenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pacjenta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPacjenta"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nazwisko");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("pesel");

                    b.HasKey("IdPacjenta");

                    b.HasIndex("PESEL")
                        .IsUnique();

                    b.ToTable("pacjent");
                });

            modelBuilder.Entity("Backend.Models.Relational.Wizyta", b =>
                {
                    b.Property<int>("IdWizyty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_wizyty");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWizyty"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<int>("IdLekarza")
                        .HasColumnType("integer")
                        .HasColumnName("id_lekarza");

                    b.Property<int>("IdPacjenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_pacjenta");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("IdWizyty");

                    b.HasIndex("Data");

                    b.HasIndex("IdLekarza");

                    b.HasIndex("IdPacjenta");

                    b.HasIndex("Status");

                    b.ToTable("wizyta");
                });

            modelBuilder.Entity("Backend.Models.Relational.Wizyta", b =>
                {
                    b.HasOne("Backend.Models.Relational.Lekarz", "Lekarz")
                        .WithMany("Wizyty")
                        .HasForeignKey("IdLekarza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Relational.Pacjent", "Pacjent")
                        .WithMany("Wizyty")
                        .HasForeignKey("IdPacjenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lekarz");

                    b.Navigation("Pacjent");
                });

            modelBuilder.Entity("Backend.Models.Relational.Lekarz", b =>
                {
                    b.Navigation("Wizyty");
                });

            modelBuilder.Entity("Backend.Models.Relational.Pacjent", b =>
                {
                    b.Navigation("Wizyty");
                });
#pragma warning restore 612, 618
        }
    }
}
